
# Generated by Django 4.1.3 on 2022-11-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('adress', models.CharField(max_length=32)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
