# Generated by Django 4.1.3 on 2023-01-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_estate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='population',
        ),
    ]
